### ISSUE TITLE
恕我直言，道友这份代码和 JPFPSStatus 这份相似度很高啊。

### ISSUE THREAD

**Issue by Jinxiansen** [wybflb/ALFPSStatus#1]
让我感到百思不得其姐。
而且实际使用的时候都没有解决加在window上的fps Label遮挡下边的状态栏图标(图标多的情况下)的问题。

**Comment by xmzqhl** [comment]
JP的是在window的rootViewController.view上加的label，AL是独立的window，主要解决的是当present一个controller的时候，FPS的状态不被遮挡。其次，JP的是不支持横竖屏旋转的，AL做了支持，无论是iPhone还是iPad都可以兼容，且由于独立window的关系，在iPhone上，window并不随着设备的旋转而旋转，进而适配花的工作量很大。譬如说在iPhone5上以横屏模式启动，譬如说竖屏启动后在横屏end，然后又在横屏start，等等奇怪问题。状态栏图标特别多的时候，是不可避免会受一点点干扰的，这也是由于没有权限直接在真正的状态栏操作的缘故，而它仅仅是一个调试工具而已，这点影响是可以忽略的(为什么一定要充着电，开着闹钟，开着蓝牙，开着定位来调试应用呢)，如果有很很多人反馈这个问题的话，后续会考虑解决。谢谢关注

**Comment by xmzqhl** [comment]
补充一下，看了JP的代码，120行代码，而AL是370行，从代码行数也已经说明了差别，另外呢，由于检测fps，是这个功能肯定会用CADisplayLink，得到帧率然后显示，那么大家的差别就在设计思路上了，AL里面为了兼容，其实是有很多黑魔法的，比如为什么设置bounds，而不是frame，window在iPhone上旋转之后的各种奇葩问题。坐标系不随着设备的旋转而改变，坐标系的判断依据，不用任何代码，自动运行，release环境自动屏蔽，判断条件的严谨，很多时候，失之毫厘谬以千里等等，可以说，楼主看到的表面的略微相似，其实背后是大有不同的。

**Comment by Jinxiansen** [comment]
🤔加油 。

**Comment by xmzqhl** [comment]
@Jinxiansen 谢谢支持！
